### ISSUE TITLE
无法使用代码高亮

### ISSUE THREAD

**Issue by ghost** [Weic96/Note-Typecho#2]
我使用的是typecho 1.0 (14.10.10)版本。
发现在写文章的时候，无论是用两个单引号包围的方式，还是用三个单引号包围的方式，都无法代码高亮，请问是需要什么插件呢还是主题就不支持代码高亮？谢谢

**Comment by machengwei1024** [comment]
引号？你确定是正确的markdown写法吗？
主题是支持代码高亮的，可参考http://www.beanan.xin/index.php/archives/22/
github不常来看，如果还有问题最好到我博客留言或直接发邮件
